# Generated by Django 4.1.2 on 2022-10-14 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=16)),
                ('senha', models.CharField(blank=True, max_length=16)),
                ('nasc', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
